backend: 
  name: github
  repo: matthewjlewis93/wine30
  api_root: https://api.github.com
  base_url: https://api.netlify.com/
  auth_endpoint: auth
media_folder: src/images
public_folder: /images
collections:
  - name: events
    label: Events
    folder: "src/_data/events"
    create: true
    extension: json
    slug: "{{year}}-{{month}}-{{day}}_{{hour}}-{{minute}}-{{second}}-{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime", date_format: true }
      - { label: "Start Time", name: "start", widget: "datetime", time_format: true }
      - { label: "End Time", name: "end", widget: "datetime", time_format: true }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "EventType", name: "eventtype", widget: "hidden", default: "event" }
      - { label: "Registration Link", name: "registration", widget: "string", required: false}

  - name: closures
    label: Holidays and Altered Hours
    folder: "src/_data/events"
    create: true
    extension: json
    slug: "{{year}}-{{month}}-{{day}}_{{hour}}-{{minute}}-{{second}}-{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: true }
      - { label: "Closed All Day?", name: "closed", widget: "boolean", default: false }
      - { label: "Open", name: "start", widget: "datetime", time_format: true, required: false}
      - { label: "Close", name: "end", widget: "datetime", time_format: true, required: false}
      - { label: "EventType", name: "eventtype", widget: "hidden", default: "closure" }

  - name: storehours
    label: Hours
    folder: "src/_data/hours"
    create: false
    extension: "json"
    sortable_fields: ["order"]
    delete: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Open", name: "open", widget: "boolean" }
      - { label: "Open Time", name: "openTime", widget: "string" }
      - { label: "Close Time", name: "closeTime", widget: "string" }
      - { label: "Order", name: "order", widget: "hidden"}

  - name: offerings
    label: Offerings
    folder: "src/_data/offerings"
    create: true
    extension: "json"
    sortable_fields: ["order"]
    delete: true
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Display Order", name: "order", widget: "number" }
      - { label: "Link Text", name: "buttonText", required: false, widget: "string" }
      - { laell: "Link Page", name: "buttonLink", required: false, widget: "string" }
      - { label: "Image", name: "image", required: false, widget: "image" }
      - { label: "Image Alt Text", name: "alttext", required: false, widget: "string" }

  - name: about
    label: About Us
    folder: "src/_data/about"
    create: false
    delete: false
    extension: "json"
    fields: 
      - { label: "Title", name: "title", widget: "hidden", default: "About Paragraph" }
      - { label: "Text", name: "text", widget: "text" }